name: Data API Astra DEV

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  JAVA_VERSION: 11
  TEST_CLASS: com.example.MySpecificTest
  PROJECT_DIRECTORY: project

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build with Maven
        run: |
          mvn install

      - name: Run test for DEV
        run: |
          cd astra-db-java
          run: mvn -Dtest=com.datastax.astra.test.integration.dev.*Test test
